### ISSUE TITLE
La page lag

### ISSUE THREAD

**Issue by AntoineNeret** [Dany70140/PigeonClicker#1]
La page lag à cause de l'affichage des pigeons quand on arrive à un certain niveau et si on continue la page finit par crash avec un seul clique

**Comment by ThomasTZTM** [comment]
Bonjour Antoine,
Le jeu est encore en développement et donc n'est pas fait pour être fonctionnel.
Merci de bien vouloir attendre la sortie du jeu.
Cordialement,
Thomas

**Comment by AntoineNeret** [comment]
Bonjour Thomas,
Je ne faisais que remonter un problème que j'ai rencontré, si vous ne voulez pas de retours des joueurs pour améliorer le jeu, il faut le dire.
Cordialement,
Antoine

**Comment by adrienb39** [comment]
test

**Comment by Roiborgne** [comment]
Excusez mon collègue,
Nous sommes bien évidemment ravis que vous, Joueurs/Testeur, nous transmettiez les problèmes que vous rencontrez.
Sachez que le problème est désormais réglé avec quelques améliorations supplémentaires.
